// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/7de6c3dd94feaeb21f20054b9f30d5dabc5efabd/yeoman-generator/yeoman-generator.d.ts
// Type definitions for yeoman-generator
// Project: https://github.com/yeoman/generator
// Definitions by: Kentaro Okuno <http://github.com/armorik83>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

declare namespace yo {

  export interface IMemFsEditor {
    copyTpl(from: string | string[], to: string, context: Object, options?: Object): void;
  }

}
